name: SPTools
version: 1.7.0
main: cn.ymjacky.SPToolsPlugin
api-version: '1.21'
folia-supported: true

author: SPDeveloper
description: 一个由 Sparkpixel 团队开发的小插件，拥有服务器定制功能
website: https://www.sparkpixel.top

softdepend:
  - Vault
  - ProtocolLib

commands:
  queue:
    description: 'Main command for the queue system'
    usage: |
      /queue join <queue name> - Join a queue
      /queue leave - Leave the queue
      /queue list - View the list of queues
      /queue info <queue name> - View queue information
  confirm:
    description: 'Confirm participation in the queue'
    usage: '/confirm'
    aliases: [ready]
  leavequeue:
    description: 离开当前队列
    usage: /leavequeue
    aliases: [leave, lq]
  insurance:
    description: Main insurance command
    usage: /insurance <toggle|gui|backup|admin|reload>
    aliases: [ins]
  stats:
    description: View player statistics
    usage: /stats [view|top|reload|help]
    aliases: [stat, statistics]

permissions:
  sptools.use:
    description: 'Allows the use of the SPTools plugin'
    default: true
  sptools.admin:
    description: 'Administer the SPTools plugin'
    default: op
    children:
      sptools.reload: true
      sptools.bypass: true
  sptools.reload:
    description: 'Allows reloading the plugin configuration'
    default: op
  sptools.bypass:
    description: 允许绕过队列限制
    default: op
  insurance.use:
    description: Allow using insurance commands
    default: true
  insurance.admin:
    description: Allow admin insurance commands
    default: op
  insurance.toggle:
    description: Allow toggling plugin feature
    default: op
  insurance.gui:
    description: Allow opening insurance GUI
    default: true
  insurance.backup:
    description: Allow opening backup GUI
    default: true
  insurance.reload:
    description: Allow reloading configuration file
    default: op