name: SPTools
version: 1.5.0
main: cn.ymjacky.SPToolsPlugin
api-version: '1.21'
folia-supported: true

author: SPDeveloper
description: 支持Folia的小游戏队列系统和物品保险系统
website: https://www.sparkpixel.top

softdepend:
  - Vault

commands:
  queue:
    description: 队列系统主命令
    usage: |
      /queue join <队列名> - 加入队列
      /queue leave - 离开队列
      /queue list - 查看队列列表
      /queue info <队列名> - 查看队列信息
    aliases: [q, waitinglist]
  confirm:
    description: 确认参与队列
    usage: /confirm
    aliases: [ready]
  leavequeue:
    description: 离开当前队列
    usage: /leavequeue
    aliases: [leave, lq]
  insurance:
    description: Main insurance command
    usage: /insurance <toggle|gui|backup|admin|reload>
    aliases: [ins]
  ins:
    description: Insurance command alias
    usage: /ins <toggle|gui|backup|admin|reload>
  stats:
    description: View player statistics
    usage: /stats [view|top|reload|help]
    aliases: [stat, statistics]

permissions:
  SPTools.use:
    description: 允许使用SPTools插件
    default: true
  SPTools.admin:
    description: 管理SPTools插件
    default: op
    children:
      SPTools.reload: true
      SPTools.bypass: true
  SPTools.reload:
    description: 允许重载插件配置
    default: op
  SPTools.bypass:
    description: 允许绕过队列限制
    default: op
  insurance.use:
    description: Allow using insurance commands
    default: true
  insurance.admin:
    description: Allow admin insurance commands
    default: op
  insurance.toggle:
    description: Allow toggling plugin feature
    default: op
  insurance.gui:
    description: Allow opening insurance GUI
    default: true
  insurance.backup:
    description: Allow opening backup GUI
    default: true
  insurance.reload:
    description: Allow reloading configuration file
    default: op
  sptools.stats:
    description: Allow viewing player statistics
    default: true
  sptools.stats.admin:
    description: Allow admin statistics commands
    default: op