name: SPTools
version: 1.0.0
main: cn.ymjacky.SPToolsPlugin
api-version: '1.20'
folia-supported: true

author: SPDeveloper
description: 支持Folia的小游戏队列系统
website: https://www.sparkpixel.top

commands:
  queue:
    description: 队列系统主命令
    usage: |
      /queue join <队列名> - 加入队列
      /queue leave - 离开队列
      /queue list - 查看队列列表
      /queue info <队列名> - 查看队列信息
    aliases: [q, waitinglist]
  confirm:
    description: 确认参与队列
    usage: /confirm
    aliases: [ready]
  leavequeue:
    description: 离开当前队列
    usage: /leavequeue
    aliases: [leave, lq]

permissions:
  SPTools.use:
    description: 允许使用SPTools插件
    default: true
  SPTools.admin:
    description: 管理SPTools插件
    default: op
    children:
      SPTools.reload: true
      SPTools.bypass: true
  SPTools.reload:
    description: 允许重载插件配置
    default: op
  SPTools.bypass:
    description: 允许绕过队列限制
    default: op