name: SPTools
version: 5.0-26.1.2
main: cn.ymjacky.SPToolsPlugin
api-version: '26.1'
folia-supported: true

author: SPDeveloper
description: 'A small plugin developed by the Sparkpixel team, featuring server customization functions'
website: https://www.sparkpixel.top

softdepend:
  - Vault
  - ProtocolLib

commands:
  queue:
    description: 'Main command for the queue system'
    usage: |
      /queue join <queue name> - Join a queue
      /queue leave - Leave the queue
      /queue list - View the list of queues
      /queue info <queue name> - View queue information
  confirm:
    description: 'Confirm participation in the queue'
    usage: '/confirm'
    aliases: [ready]
  leavequeue:
    description: 'Leave current queue'
    usage: /leavequeue
    aliases: [leave, lq]
  rmbbars:
    description: 'Remove all bossbars'
    usage: /rmbbars
    aliases: [removebossbars]

permissions:
  sptools.use:
    description: 'Allows the use of the SPTools plugin'
    default: true
  sptools.admin:
    description: 'Administer the SPTools plugin'
    default: op
    children:
      sptools.reload: true
      sptools.bypass: true
  sptools.reload:
    description: 'Allows reloading the plugin configuration'
    default: op
  sptools.bypass:
    description: 'Allows bypass the limits of queue'
    default: op
  removebossbars.use:
    description: 'Allows remove all bossbar'
    default: op
