name: SPTools
version: 1.0.0
main: cn.ymjacky.SPToolsPlugin
api-version: '1.20'
folia-supported: true
depend: [ ProtocolLib ]

author: SPDeveloper
description: A wonderful plugin for fulfilling various needs of the Sparkpixel server.
website: https://www.sparkpixel.top

commands:
  queue:
    description: 'Main command for the queue system'
    usage: |
      /queue join <queue name> - Join a queue
      /queue leave - Leave the queue
      /queue list - View the list of queues
      /queue info <queue name> - View queue information
  confirm:
    description: 'Confirm participation in the queue'
    usage: '/confirm'
    aliases: [ready]
  leavequeue:
    description: 'Leave the current queue'
    usage: '/leavequeue'

permissions:
  SPTools.use:
    description: 'Allows the use of the SPTools plugin'
    default: true
  SPTools.admin:
    description: 'Administer the SPTools plugin'
    default: op
    children:
      SPTools.reload: true
      SPTools.bypass: true
  SPTools.reload:
    description: 'Allows reloading the plugin configuration'
    default: op
  SPTools.bypass:
    description: 'Allows bypassing queue restrictions'
    default: op