name: SPTools
version: 1.5.0
main: cn.ymjacky.SPToolsPlugin
api-version: '1.21'
folia-supported: true
depend: [ ProtocolLib ]

author: SPDeveloper
description: 支持Folia的小游戏队列系统和物品保险系统
website: https://www.sparkpixel.top

softdepend:
  - Vault

commands:
  queue:
    description: 'Main command for the queue system'
    usage: |
      /queue join <queue name> - Join a queue
      /queue leave - Leave the queue
      /queue list - View the list of queues
      /queue info <queue name> - View queue information
  confirm:
    description: 'Confirm participation in the queue'
    usage: '/confirm'
    aliases: [ready]
  leavequeue:
    description: 离开当前队列
    usage: /leavequeue
    aliases: [leave, lq]
  insurance:
    description: Main insurance command
    usage: /insurance <toggle|gui|backup|admin|reload>
    aliases: [ins]
  stats:
    description: View player statistics
    usage: /stats [view|top|reload|help]
    aliases: [stat, statistics]

permissions:
  SPTools.use:
    description: 'Allows the use of the SPTools plugin'
    default: true
  SPTools.admin:
    description: 'Administer the SPTools plugin'
    default: op
    children:
      SPTools.reload: true
      SPTools.bypass: true
  SPTools.reload:
    description: 'Allows reloading the plugin configuration'
    default: op
  SPTools.bypass:
    description: 允许绕过队列限制
    default: op
  insurance.use:
    description: Allow using insurance commands
    default: true
  insurance.admin:
    description: Allow admin insurance commands
    default: op
  insurance.toggle:
    description: Allow toggling plugin feature
    default: op
  insurance.gui:
    description: Allow opening insurance GUI
    default: true
  insurance.backup:
    description: Allow opening backup GUI
    default: true
  insurance.reload:
    description: Allow reloading configuration file
    default: op
  sptools.stats:
    description: Allow viewing player statistics
    default: true
  sptools.stats.admin:
    description: Allow admin statistics commands
    default: op